# Generated by Django 4.2 on 2024-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=30)),
            ],
        ),
    ]
